name: parses
version: 0.1.0.0
github: "githubuser/parses"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/parses#readme>

dependencies:
  - base >= 4.7 && < 5
  - old-locale >=1.0.0.2 && <1.1
  - filepath
  - Win32 >=2.5 && <2.12
  - mtl > 1.0 && <=2.2.2
library:
  source-dirs: src

executables:
  parses-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - parses

tests:
  parses-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - parses
